# Here you can unlimited amount of groups. To apply a group to a user just add the permission mt.payment.{group}
message:
    added_money: "&7You got &e{amount}$ &7added to your account"
groups:
    default:
        interval: 60    # interval in minutes
        amount: 100     # amount of money to pay per interval
    bronze:
        interval: 30
        amount: 200
    silver:
        interval: 15
        amount: 300
    gold:
        interval: 5
        amount: 400
    platinum:
        interval: 1
        amount: 500