name: MoneyTime
version: 1.0
api-version: 1.20
main: me.nashplugz.mtnp.MoneyTime
depend: [Vault]
commands:
  moneytime:
    description: Main command for the MoneyTime plugin.
    usage: /moneytime [reload]
    permission: moneytime.command
    aliases:
      - mt
permissions:
  moneytime.command.*:
    description: Allows the user to use the whole moneytime command.
    default: op
    children:
      moneytime.command.reload: true
  moneytime.command.reload:
    description: Allows the user to reload the plugin.
    default: op